---
cluster_name: RACSCL
scan_name: racs-scan
scan_ip:
  - 192.168.56.84
  - 192.168.56.85
  - 192.168.56.86

node1_name: racs1
node2_name: racs2
node1_public_ip: 192.168.56.80
node2_public_ip: 192.168.56.81
node1_vip: 192.168.56.82
node2_vip: 192.168.56.83

grid_user: grid
oracle_user: oracle
oracle_base: /u01/app/oracle
grid_base: /u01/app/grid
grid_home: /u01/app/26ai/grid
oracle_home: /u01/app/oracle/product/26ai/dbhome_1
ora_inventory: /u01/app/oraInventory
stage_dir: /stage/26ai

ansible_remote_tmp: /u01/.ansible/tmp

sys_password: "racattack"
asm_monitor_password: "racattack"

ocr_diskgroup: OCR
data_diskgroup: DATA
fra_diskgroup: FRA

ocr_disks:
  - /dev/asm/OCR01

data_disks:
  - /dev/asm/DATA01

fra_disks:
  - /dev/asm/FRA01

public_interface: enp0s3
private_interface: enp0s8

public_subnet: 192.168.56.0
private_subnet: 192.168.57.0

asmadmin_group: asmadmin
asmdba_group: asmdba
asmoper_group: asmoper


grid_zip: LINUX.X64_2326100_grid_home.zip
db_zip: LINUX.X64_2326100_db_home.zip

ocr_disks:
  - /dev/disk/by-id/ata-VBOX_HARDDISK_VBddaa40bb-7a1b3dc7
data_disks:
  - /dev/disk/by-id/ata-VBOX_HARDDISK_VB73715a8d-a73c68c9
fra_disks:
  - /dev/disk/by-id/ata-VBOX_HARDDISK_VB1c21c696-703123cf
