- name: Verify connectivity to RAC nodes
  hosts: all
  gather_facts: false

  tasks:

    - name: Ping hosts
      ansible.builtin.ping:

    - name: Show hostname
      ansible.builtin.command: hostname
      register: host

    - name: Display hostname
      ansible.builtin.debug:
        var: host.stdou
