---
- name: Verify connectivity to RAC nodes
  hosts: all
  gather_facts: false

  tasks:

    - name: Ping hosts
      ansible.builtin.ping:

    - name: Get hostname
      ansible.builtin.command: hostname
      register: host

    - name: Display hostname
      ansible.builtin.debug:
        msg: "Connected to {{ host.stdout }}"
